import type { DashboardData } from '../types/dashboard'

export const mockDashboardData: DashboardData = {
  metrics: [
    {
      title: 'Total Transactions',
      value: '124,892',
      delta: '+8.2%',
      trend: 'up',
    },
    {
      title: 'Suspicious Flags',
      value: '1,284',
      delta: '+3.7%',
      trend: 'up',
    },
    {
      title: 'Fraud Rate',
      value: '1.03%',
      delta: '-0.2%',
      trend: 'down',
    },
    {
      title: 'Avg Review Time',
      value: '2m 14s',
      delta: '-11.4%',
      trend: 'down',
    },
  ],
  volumeSeries: [
    { label: 'Mon', transactions: 18200, suspicious: 210 },
    { label: 'Tue', transactions: 19600, suspicious: 248 },
    { label: 'Wed', transactions: 20100, suspicious: 267 },
    { label: 'Thu', transactions: 21500, suspicious: 295 },
    { label: 'Fri', transactions: 22800, suspicious: 322 },
    { label: 'Sat', transactions: 17300, suspicious: 187 },
    { label: 'Sun', transactions: 15300, suspicious: 155 },
  ],
  riskDistribution: [
    { name: 'Low Risk', value: 72 },
    { name: 'Medium Risk', value: 19 },
    { name: 'High Risk', value: 9 },
  ],
  suspiciousTransactions: [
    {
      id: 'TXN-90214',
      userId: 'USR-1882',
      amount: '$4,820.00',
      location: 'Berlin, DE',
      riskLevel: 'HIGH',
      status: 'SUSPICIOUS',
      timestamp: '2 min ago',
    },
    {
      id: 'TXN-90211',
      userId: 'USR-2041',
      amount: '$1,275.00',
      location: 'Istanbul, TR',
      riskLevel: 'MEDIUM',
      status: 'SUSPICIOUS',
      timestamp: '5 min ago',
    },
    {
      id: 'TXN-90197',
      userId: 'USR-0912',
      amount: '$8,140.00',
      location: 'London, UK',
      riskLevel: 'HIGH',
      status: 'SUSPICIOUS',
      timestamp: '11 min ago',
    },
    {
      id: 'TXN-90184',
      userId: 'USR-3018',
      amount: '$684.00',
      location: 'Madrid, ES',
      riskLevel: 'MEDIUM',
      status: 'SUSPICIOUS',
      timestamp: '19 min ago',
    },
    {
      id: 'TXN-90173',
      userId: 'USR-7712',
      amount: '$325.00',
      location: 'Paris, FR',
      riskLevel: 'LOW',
      status: 'NORMAL',
      timestamp: '24 min ago',
    },
  ],
  recentActivity: [
    {
      id: 'ACT-1',
      title: 'Velocity rule triggered',
      description: 'User USR-1882 exceeded the 1-minute threshold.',
      time: '2 min ago',
      severity: 'critical',
    },
    {
      id: 'ACT-2',
      title: 'Amount anomaly detected',
      description: 'Transaction TXN-90197 exceeded 3x 24h average.',
      time: '11 min ago',
      severity: 'warning',
    },
    {
      id: 'ACT-3',
      title: 'Worker processed queue batch',
      description: 'fraud-worker-service completed 250 evaluations.',
      time: '18 min ago',
      severity: 'info',
    },
    {
      id: 'ACT-4',
      title: 'MCP read endpoint ready',
      description: 'mcp-server-service placeholder route responding.',
      time: '26 min ago',
      severity: 'info',
    },
  ],
}