spring:
  application:
    name: transaction-api-service

  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/fraud_platform
    username: fraud_user
    password: fraud_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: fraud_admin
    password: fraud_admin_pass

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    rabbit:
      enabled: false